- id: black
  name: Black
  entry: black
  language: python
  types: [python]
  additional_dependencies: [black==24.8.0]

- id: flake8
  name: Flake8
  entry: flake8
  language: python
  types: [python]
  additional_dependencies: [flake8==7.1.1]

